version: 2.1

commands:
  print_pipeline_id:
    description: "Prints the pipeline id"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  reuseable-code:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id

workflows:
  pipeline_id: 
    jobs:
      - reuseable-code